이제 R에서 파이썬으로 옮겨가기 위한 연습을 해보자.

자료는 내가 유전학 연구실에서 정리했던 것이다. 똑같은 작업을 파이썬을 통해서 해보자.

In [20]:
import numpy as np
import pandas as pd
import os

In [21]:
# show current directory
os.chdir("/home/dabuntu/Materials/RtoPython/Alc&Smk/")

os.listdir()

['CNTY06.ASC',
 'CNTY05.ASC',
 'newfile.txt',
 'CNTY08.ASC',
 'CNTY03.ASC',
 'CNTY02.ASC',
 'CNTY09.ASC',
 'CNTY10.ASC',
 'CNTY04.ASC',
 'ThisIndex.csv',
 'CNTY11.ASC',
 'CNTY07.ASC',
 'CNTY12.asc']

In [51]:
# make dummy dataframe
survey_df = pd.DataFrame( {
    'STATE': np.zeros(15),
    'SMOKER2': np.zeros(15),
    'DROCDY_': np.zeros(15),
    'BINGE': np.zeros(15),
    'MRACE': np.zeros(15),
    'RACE2': np.zeros(15),
    'AGE5YR' : np.zeros(15),
    'SEX' : np.zeros(15),
    'COUNTYNAME': np.zeros(15)
})

survey_df = survey_df[ ["Type", "2002", "2003", "2004", "2005", "2006", 
                        "2007", "2008", "2009", "2010", "2011", "2012"]]

survey_df["Type"] = index_file["Type"]

survey_df

,Type,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,STATE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,SMOKE100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SMOKEDAY,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,STOPSMK2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ALCDAY3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,AVEDRNK,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,SEX,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,_SMOKER2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,DROCCDY_,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,BINGE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,DRNKMO2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,_MRACE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,RACE2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,AGEG5YR,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,COUNTYNAME,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [50]:
# read index and set rules
index_file = pd.read_csv("ThisIndex.csv",)
index_file

,Type,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,STATE,1-2,1-2,1-2,1-2,1-2,1-2,1-2,1-2,1-2,1-2,1-2
1,SMOKE100,108,99,70,82,79,84,81,83,83,63,88
2,SMOKEDAY,109,100,71,83,80,85,82,84,84,64,89
3,STOPSMK2,110,101,72,84,81,86,83,85,85,65,90
4,ALCDAY3,111-113,102-104,73-75,86-88,114-116,129-131,121-123,129-132,121-123,165-167,94-96
5,AVEDRNK,114-115,105-106,76-77,89-90,117-118,132-133,124-125,132-133,124-125,168-169,97-98
6,SEX,149,140,119,128,110,117,118,123,118,107,84
7,_SMOKER2,878,381,369,411,372,405,367,471,458,201,193
8,DROCCDY_,880-882,383-385,371-373,413-415,420-422,453-455,415-417,519-521,506-508,387-389,196-198
9,BINGE,884,387,375,416,423,456,418,522,509,390,199
10,DRNKMO2,889-892,392-395,380-383,421-424,428-431,461-464,423-426,527-530,514-517,395-398,204-207
11,_MRACE,913-914,413-414,409-410,442-443,388-389,421-422,383-384,487-488,474-475,217-218,163-164
12,RACE2,915,415,411,444,395,428,385,489,476,219,165
13,AGEG5YR,920-921,420-421,417-418,450-451,396-397,429-430,391-392,495-496,482-483,225-226,169-170
14,COUNTYNAME,958-989,491-540,478-527,542-591,473-522,535-584,468-507,618-667,559-608,413-415,232-281

In [74]:
file_list = sorted(os.listdir())[1:len(os.listdir())-2]
file_list

['CNTY02.ASC',
 'CNTY03.ASC',
 'CNTY04.ASC',
 'CNTY05.ASC',
 'CNTY06.ASC',
 'CNTY07.ASC',
 'CNTY08.ASC',
 'CNTY09.ASC',
 'CNTY10.ASC',
 'CNTY11.ASC',
 'CNTY12.asc']

In [75]:
k = 1

for i in file_list :
    print (i)
    with open(i, 'r') as r :
            while True:
                line = r.readline()
                for j in range(15):
                    ind = index_file.iloc[:,k]
                    if( '-' in ind[j]) :
                        start, end = map(int,ind[j].split('-'))
                        survey_df.iloc[j, k] = line[start-1: end]

                    else :
                        start = int(ind[j])-1
                        end = int(ind[j])-1
                        survey_df.iloc[j, k] = line[start: end+1]
                if not line :
                    break
    print("File ",i, " Finished.")
    k += 1

CNTY02.ASC

KeyboardInterrupt:

In [76]:
survey_df

,Type,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012
0,STATE,17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,SMOKE100,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,SMOKEDAY,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,STOPSMK2,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ALCDAY3,888,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,AVEDRNK,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,SEX,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,_SMOKER2,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,DROCCDY_,014,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,BINGE,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,DRNKMO2,0004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,_MRACE,01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,RACE2,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,AGEG5YR,04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,COUNTYNAME,Cook County,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0